style:
    footer:
        text-color: '#303446'
        background-color: '#8caaee'
        number-color: '#FFFFFF'
    selected-row:
        text-color: '#303446'
        background-color: '#a6d189'
    result-row:
        number-color: '#e78284'
        directory-color: '#85c1dc'
    header:
        text-color: '#303446'
        background-color: '#8caaee'
        hidden: false
    progress-modal:
        current-item-path-max-len: 0
    use-old-size-bar: false
sorting:
    by: ""
    order: ""
log-file: /dev/null
input-file: ""
output-file: ""
ignore-from-file: ""
storage-path: /tmp/badger
ignore-dirs:
    - /proc
    - /dev
    - /sys
    - /run
ignore-dir-patterns: []
max-cores: 14
top: 0
sequential-scanning: false
show-apparent-size: false
show-relative-size: false
show-annexed-size: false
show-item-count: false
show-mtime: false
no-color: false
mouse: false
non-interactive: false
no-progress: false
no-unicode: false
no-cross: false
no-hidden: false
no-delete: false
no-spawn-shell: false
follow-symlinks: false
profiling: false
const-gc: false
use-storage: false
read-from-storage: false
summarize: false
use-si-prefix: false
no-prefix: false
reverse-sort: false
change-cwd: false
delete-in-background: false
delete-in-parallel: false
